spring:
  application:
    name: moit-api
  config:
    import:
      - application-domain.yml

  # OAuth login
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: ${AUTH0_ISSUER_URI}

# swagger doc 
springdoc:
  packages-to-scan: com.mashup.moit
  swagger-ui:
    path: /api-docs
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

# Actuator 정보
management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: "/am-i-alive"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details : always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  server:
    port: 8077
