spring:
  application:
    name: moit-api
  profiles:
    default: dev
  config:
    import:
      - classpath:/application-domain.yml

  # OAuth login
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ENC(NNbSuxBd5Gl+LZJwCws0IYoYmA2Pe4+sX0Hm7+QToWpU1F5HFQg7jLVy6phcyTdcUc2NXUtul8jYJZCV5AGaVAxyPQX75r2KkwJQ7Zcjqkw=)
            client-secret: ENC(sruib4iDMuuI7Z5anBNzBf89Zoi1mZ7EII1pml9sO9kAOydk1YDhpEUb6gscCvXIkkGiShNQ+Y8fMXv129DMORolgW3AF2lRyMhnpryxRABTgJ5mUTSkH/thUb/Y6ejSH9SBQUu7AJV1OtEZonJ3lg==)
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: ENC(G0yAcdZjTXv3nDDqIA8AKZs7ec6+Trbo7Fo/CNvDMcqNlr6h+7VHIDbjtA9A5QAH7LARlMBuv7IOh+SnHXAzU4+2MzrciU3DygNAjvI5ckw=)
  
# swagger doc 
springdoc:
  packages-to-scan: com.mashup.moit
  swagger-ui:
    path: /api-docs
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

# Actuator 정보
management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: "/am-i-alive"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  server:
    port: 8077

moit:
  auth:
    jwt-secret-key: ENC(011c274SIytPrr5ozweLG7iWoGQVAMo1uA8xRAFyBASndo9yGYtfmDtBO7TchnzRJWVJiauSVzX5LX/XD/3NieuTBKcETvYEjgvo9znrniw=)
  security:
    allow-origins:
      - http://localhost:5173
      - http://localhost:4173
      - ENC(uXx5O7pACezVpodzx1cbvPVb+4qQefsL8u235ZWRD4hP2IThgOgIla6BJVEupoNI6IB564Isk2I/K7brxrJDJg==)
      - ENC(lworToUh9KWXM1aod0J7cFCe/iblZzRNkR5V+geeZrW3TfgKqT7o2JpbdBO+AV7O8g79HWp0E39Gu2PebYj1mQ==)
      - ENC(/jAyQYtRBByj4rWxyv/CEK8zd2V5HV3QqxHFQfKsjHou3YoLpgRqeIIJWH5nfCMjg0cys/v6ZeVoXlCmK+c17UDRU+Qx5/DqmEacdIH+FS+odPTL2GihuS05Vj+n6KSt)

cloud:
  aws:
    credentials:
      access-key: ENC(59QcBpydXsm/54kH3O8aPU6bPuTIdxpCTet6FuU5XC5z5Zwi52AfYlTjyjxZwPWyBM1AaI8lW+FZYQnwzP6hBw==)
      secret-key: ENC(V1ZQWaHkDE5DgMCB+9zKg7zGG6L9fZGXMCI0+iwPrX2/7cu79E60tVxQQ1MWh4taVLMwjaE3nptBBuRIIeIfguvilK91bO+lBU/9Ue//g0Y=)
    s3:
      domain: ENC(7F1WPrRa7fvFEYOfGsTFYIhe7R5bQmmCJMwgghCEvPOB7/4SipK+Nnr5EEED0JUICQUtoRUzPmPBNhQ5QXS+2KD4vhmEYkkh3jOT8Lqr1KDITPcs41c7J7m1/6lf74DO)
      bucket-name: ENC(/sQSONSoi0685DnJHPl4WSRI8E5ARagYcbvkA15RUWTcH5s6wAgMut0+A7EqDQeXQT8FR97Kbpt2FacUNQrg3Q==)
    cloudwatch:
      access-key: {aws_access_key}
      secret-key: {aws_secret_key}
    region:
      static: "ap-northeast-2"
      auto: false

fcm:
  certification: firebase/moit-firebase-adminsdk.json

server:
  forward-headers-strategy: FRAMEWORK
