spring:
  application:
    name: moit-api
  profiles:
    default: dev
  config:
    import:
      - classpath:/application-domain.yml

  # OAuth login
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ENC(6jkKllTGxVAzzWlIpGfYWOi/8xNw1/BYMDURjaq/W5WDk9mpxQT/m1ONh5hnOUl/dQwSAA7ZzGdItniu3xH7vFdHGSmpl5lDYiV7VEfRBd0=)
            client-secret: ENC(ut0qWQvWin/brPbolIE6FWQEOYm73alrD9QkzkGWFqwjIHzjGtABrniR8VB5n+BmTe2lJuQ9x5KsjyKZ+Qu5Vy0KUNc42LhtWO+y8y3FwK5nwri5lnPEXR1Hg0sXQItoDGLOym79bHsvGQVRTCTHvg==)
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: ENC(FjcoFhmUB80mv7Ko4HuZqEyjEJ+Nr1rEF5/Ml2oSxYDG3W1F6Lw/fM19GIt4s41d7467ujASDQjd8FZnGksdnRukTGCQLFEYOrb3iYnIX2w=)

  # OAuth login
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ENC(6jkKllTGxVAzzWlIpGfYWOi/8xNw1/BYMDURjaq/W5WDk9mpxQT/m1ONh5hnOUl/dQwSAA7ZzGdItniu3xH7vFdHGSmpl5lDYiV7VEfRBd0=)
            client-secret: ENC(ut0qWQvWin/brPbolIE6FWQEOYm73alrD9QkzkGWFqwjIHzjGtABrniR8VB5n+BmTe2lJuQ9x5KsjyKZ+Qu5Vy0KUNc42LhtWO+y8y3FwK5nwri5lnPEXR1Hg0sXQItoDGLOym79bHsvGQVRTCTHvg==)
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: ENC(FjcoFhmUB80mv7Ko4HuZqEyjEJ+Nr1rEF5/Ml2oSxYDG3W1F6Lw/fM19GIt4s41d7467ujASDQjd8FZnGksdnRukTGCQLFEYOrb3iYnIX2w=)

# swagger doc 
springdoc:
  packages-to-scan: com.mashup.moit
  swagger-ui:
    path: /api-docs
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

# Actuator 정보
management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: "/am-i-alive"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details : always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  server:
    port: 8077
