spring:
  datasource:
    url: ENC(NncOOchYrbH3blrRsmFJ8APcqXostFc/cHWFd7nHndXR8Q5gHHXkXDRWZ6K4N71tzJxBpbVGnMMjEdXZYpxooja/YheN4UC6uNIXh5ICIy5cAvlNXY9SK21yKC0mDX6dvwLaThMdMtpnIkIwaN2M6+mwF9YOoGhlGPtJoh3XRMYoHOE4HvAaSE8Up/qctWdcbf1SSG0yUouAOLP1rsif5Q==)
    username: ENC(S15YPWgV6Q0/Q+5vFIm2BA1MrMpwobIByFummkx64mvQkIb1sS9k8V5pYNTsCKki)
    password: ENC(bNk0/MtmiFzRpWZAXjATJCUSLjFgcsfv9OYxrJGDCuqHCjcpvscstVbr2uhS3OPN)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 추후 엔티티 설정 완료 후, none 으로 변경 (필요시에만 update)
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc.lob.non_contextual_creation: true # if not, error occurs Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
