spring:
  datasource:
    url: ENC(k96tYIOmMfKx0YFXWwOfjVmFlXi1pyPmpyQlWVVg8fj6MaSy/vn4KmbpvZ4Var+MYVMpqz1XpNgzIy1cixUZwma+KNbKzRPjrd8B4xktBan2GRsPT9tgpzfhTWeCM5LaZS+O98w+XLZ2dsIVG6l1hhomxULqtzRmLhB+aFhvBGv6LS3aTgKCeuleOAbDSyAs+3/x/is049B/egivUc2m4Q==)
    username: ENC(S15YPWgV6Q0/Q+5vFIm2BA1MrMpwobIByFummkx64mvQkIb1sS9k8V5pYNTsCKki)
    password: ENC(bNk0/MtmiFzRpWZAXjATJCUSLjFgcsfv9OYxrJGDCuqHCjcpvscstVbr2uhS3OPN)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 추후 엔티티 설정 완료 후, none 으로 변경 (필요시에만 update)
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc.lob.non_contextual_creation: true # if not, error occurs Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
