spring:
  jpa:
    hibernate:
      ddl-auto: update # 추후 엔티티 설정 완료 후, none 으로 변경 (필요시에만 update)
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        
