name: CD
on:
  push:
    branches:
      - master

env:
  JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Get CurrentTime
        uses: 1466587594/get-current-time@v2
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - run: chmod +x gradlew && ./gradlew build

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 도커 이미지 빌드 & 푸시
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: electroncorps/moit-api:latest
          
      - run: |
          cd deploy && zip -r deploy.zip .

      - run: ls

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_BEANSTALK_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_BEANSTALK_SECRET_KEY }}
          application_name: moit-backend-eb-app
          environment_name: moit-backend-eb-env
          version_label: moit-deploy-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: ./deploy/Dockerrun.aws.json
          wait_for_deployment: false
